### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Expecho** [Expecho/Policy-Initiative-Bicep-Builder#1]
- [x] Wait for policies to be loaded before being able to do actions
- [ ] Download bicep as file
- [ ] After choosing a file, hide the file picker
- [ ] Reset option
- [ ] Select scope for gettting policy definitions
- [ ] Create easy deploy option
